default_settings: null
behaviors:
  WallPlacer:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: linear
      epsilon_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple
      memory: null
      goal_conditioning_type: hyper
      deterministic: false
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
        network_settings:
          normalize: false
          hidden_units: 128
          num_layers: 2
          vis_encode_type: simple
          memory: null
          goal_conditioning_type: hyper
          deterministic: false
    init_path: null
    keep_checkpoints: 5
    checkpoint_interval: 10000
    max_steps: 50000000
    time_horizon: 1
    summary_freq: 128
    threaded: true
    self_play: null
    behavioral_cloning: null
engine_settings:
  width: 84
  height: 84
  quality_level: 5
  time_scale: 5
  target_frame_rate: -1
  capture_frame_rate: 60
  no_graphics: true
